describe('RTMS Manage User Test',()=>{
    it('enable Fix Costcenter',()=>{
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการข้อมูลผู้ใช้
        cy.get('div[class="home"]').eq(1).should('be.visible').click() // จัดการสิทธิ์การใช้งาน
        cy.get('button[class="btn btn-info"]').eq(1).should('be.visible').click() // แก้ไข
        cy.scrollTo('bottom')
        cy.get('input[type="checkbox"]').eq(31).should('be.visible').click() // เปิดจัดการ Fix Costcenter
        cy.wait(3000)
        cy.get('button[class="btn btn-success"]').should('be.visible').click() // เพิ่ม
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click() // OK
    })
    it('test check menu by log out then log in',()=>{
        cy.get('div[class="b_logout"]').should('be.visible').click() // log out
        cy.wait(5000)
       cy.get('body').type('{1}{4}', { delay: 0 })
        cy.get('div[class="home"]').eq(5).should('be.visible').click() // ตั้งค่าขั้นสูง
        cy.log('Found Fix Costcenter menu')
        cy.wait(1000)
    })
    it('insert Costcenter and Test process',()=>{
        cy.get('div[class="home"]').eq(1).should('be.visible').click() // จัดการงาน
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[id="cost_center_header_name"]').should('be.visible').click()
        cy.get('button[id="kb_1"]').contains('1').should('be.visible').click()
        cy.get('button[id="kb_2"]').contains('2').should('be.visible').click()
        cy.get('button[id="kb_3"]').contains('3').should('be.visible').click()
        cy.get('button[id="kb_4"]').contains('4').should('be.visible').click()
        cy.get('button[id="kb_5"]').contains('5').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="ant-switch ant-switch-checked"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('input[id="cost_center_header_name"]').should('be.visible').click()
        cy.get('button[id="kb_6"]').contains('6').should('be.visible').click()
        cy.get('button[id="kb_7"]').contains('7').should('be.visible').click()
        cy.get('button[id="kb_8"]').contains('8').should('be.visible').click()
        cy.get('button[id="kb_9"]').contains('9').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="ant-switch ant-switch-checked"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(2).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('td[class="text-info text-center align-middle"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(2).should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_P"]').contains('P').should('be.visible').click()
        cy.get('button[id="kb_U"]').contains('U').should('be.visible').click()
        cy.get('button[id="kb_R"]').contains('R').should('be.visible').click()
        cy.get('button[id="kb_I"]').contains('I').should('be.visible').click()
        cy.get('button[id="kb_N"]').contains('N').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_1"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.scrollTo('bottom')
        cy.get('div[class="home"]').eq(9).should('be.visible').click() // จัดการ Fix Costcenter
    })
    it('insert TEST001,002 Fix Costcenter',()=>{
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_1"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="ml-1"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="ml-1"]').eq(1).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_2"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="ml-1"]').eq(2).should('be.visible').click()
        cy.get('input[class="form-check-input"]').eq(1).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
    })
    it('select manage user',()=>{
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการข้อมูลผู้ใช้
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการผู้ใช้
    })
    it('search TESTER 003 user',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_3"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
    })
    it('add TESTER 003 and Test process',()=>{
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click()
        cy.get('button[id="kb_1"]').contains('1').should('be.visible').click()
        cy.get('button[id="kb_2"]').contains('2').should('be.visible').click()
        cy.get('button[id="kb_3"]').contains('3').should('be.visible').click()
        cy.get('button[id="kb_4"]').contains('4').should('be.visible').click()
        cy.get('button[id="kb_5"]').contains('5').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(2).should('be.visible').click()
        cy.get('button[id="kb_6"]').contains('6').should('be.visible').click()
        cy.get('button[id="kb_8"]').contains('8').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(3).should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_R"]').contains('R').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(4).should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_3"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').eq(0).should('be.visible').click() // สิทธิ์การใช้งาน
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').eq(1).should('be.visible').click() // แผนก
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').eq(2).should('be.visible').click() // กลุ่มการเข้าถึงสินค้า
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(5).should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_4"]').contains('4').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_@"]').contains('@').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_g"]').contains('g').should('be.visible').click()
        cy.get('button[id="kb_m"]').contains('m').should('be.visible').click()
        cy.get('button[id="kb_a"]').contains('a').should('be.visible').click()
        cy.get('button[id="kb_i"]').contains('i').should('be.visible').click()
        cy.get('button[id="kb_l"]').contains('l').should('be.visible').click()
        cy.get('button[id="kb_."]').contains('.').should('be.visible').click()
        cy.get('button[id="kb_c"]').contains('c').should('be.visible').click()
        cy.get('button[id="kb_o"]').contains('o').should('be.visible').click()
        cy.get('button[id="kb_m"]').contains('m').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').eq(3).should('be.visible').click() // ภาษา
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').eq(4).should('be.visible').click() // fix costcenter
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
    })
    it('Test log out then log in with new user (1)',()=>{
        cy.get('svg[stroke="currentColor"]').should('be.visible').click()
        cy.wait(4000)
        cy.get('body').type('68',{delay: 0})
        cy.get('label[style="padding-top: 10px;"]').contains('TESTER 003')
    })
    it('search found TESTER 003 user',()=>{
        cy.get('div[class="home"]').eq(5).should('be.visible').click() // ตั้งค่าขั้นสูง
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการข้อมูลผู้ใช้
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการผู้ใช้
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_3"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
    })
    it('check data by relation of TESTER 003',()=>{
        cy.get('button[class="btn btn-info"]').eq(2).should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.scrollTo('bottom')
        cy.get('div[class="home"]').eq(9).should('be.visible').click() // จัดการ Fix Costcenter
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('div[class="home"]').eq(1).should('be.visible').click() // จัดการงาน
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('update TESTER 003 and change data',()=>{
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการข้อมูลผู้ใช้
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการผู้ใช้
        cy.get('button[class="btn btn-info"]').eq(2).should('be.visible').click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').clear() // รหัสพนักงาน
        cy.get('input[class="form-control"]').eq(2).should('be.visible').clear() // RFID
        cy.get('input[class="form-control"]').eq(4).should('be.visible').clear() // นามสกุล
        cy.get('input[class="form-control"]').eq(5).should('be.visible').clear() // Email
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click() // รหัสพนักงาน
        cy.get('button[id="kb_6"]').contains('6').should('be.visible').click() 
        cy.get('button[id="kb_7"]').contains('7').should('be.visible').click()
        cy.get('button[id="kb_8"]').contains('8').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').eq(4).should('be.visible').click() // fix costcenter
        cy.get('td[class="ant-table-cell"]').eq(2).should('be.visible').click()
        cy.get('input[class="form-control"]').eq(2).should('be.visible').click() // RFID
        cy.get('button[id="kb_9"]').contains('9').should('be.visible').click()
        cy.get('button[id="kb_1"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(4).should('be.visible').click() // นามสกุล
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_4"]').contains('4').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(5).should('be.visible').click() // Email
        cy.get('button[id="kb_3"]').contains('3').should('be.visible').click()
        cy.get('button[id="kb_3"]').contains('3').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_@"]').contains('@').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_h"]').contains('h').should('be.visible').click()
        cy.get('button[id="kb_o"]').contains('o').should('be.visible').click()
        cy.get('button[id="kb_t"]').contains('t').should('be.visible').click()
        cy.get('button[id="kb_m"]').contains('m').should('be.visible').click()
        cy.get('button[id="kb_a"]').contains('a').should('be.visible').click()
        cy.get('button[id="kb_i"]').contains('i').should('be.visible').click()
        cy.get('button[id="kb_l"]').contains('l').should('be.visible').click()
        cy.get('button[id="kb_."]').contains('.').should('be.visible').click()
        cy.get('button[id="kb_c"]').contains('c').should('be.visible').click()
        cy.get('button[id="kb_o"]').contains('o').should('be.visible').click()
        cy.get('button[id="kb_m"]').contains('m').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
    })
    it('Test log out then log in with new user (2)',()=>{
        cy.get('svg[stroke="currentColor"]').should('be.visible').click()
        cy.wait(4000)
        cy.get('body').type('91',{delay: 0})
        cy.get('label[style="padding-top: 10px;"]').contains('TESTER 004')
    })
    it('search not found TESTER 003 user',()=>{
        cy.get('div[class="home"]').eq(5).should('be.visible').click() // ตั้งค่าขั้นสูง
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการข้อมูลผู้ใช้
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการผู้ใช้
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_3"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
    })
    it('search found TESTER 004 user',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_4"]').contains('4').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
    })
    it('check data by relation of TESTER 004',()=>{
        cy.get('button[class="btn btn-info"]').eq(2).should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.scrollTo('bottom')
        cy.get('div[class="home"]').eq(9).should('be.visible').click() // จัดการ Fix Costcenter
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('div[class="home"]').eq(1).should('be.visible').click() // จัดการงาน
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('delete TESTER 004 user + relation',()=>{
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการข้อมูลผู้ใช้
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการผู้ใช้
        cy.get('button[class="btn btn-danger"]').eq(1).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.scrollTo('bottom')
        cy.get('div[class="home"]').eq(9).should('be.visible').click() // จัดการ Fix Costcenter
        cy.get('button[class="btn btn-danger"]').eq(1).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-danger"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('div[class="home"]').eq(1).should('be.visible').click() // จัดการงาน
        cy.get('button[class="btn btn-danger"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-danger"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('search not found TESTER 004 user',()=>{
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการข้อมูลผู้ใช้
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการผู้ใช้
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_4"]').contains('4').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
    })
    it('Log out and return to admin CTO',()=>{
        cy.get('svg[stroke="currentColor"]').should('be.visible').click()
        cy.wait(4000)
       cy.get('body').type('{1}{4}', { delay: 0 })
        cy.get('label[style="padding-top: 10px;"]').contains('admin CTO')
    })
})