describe('RTMS Create Locker Test',()=>{
    it('select manage locker',()=>{
        cy.get('div[class="home"]').eq(7).should('be.visible').click() // จัดการตู้
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการตู้
    })
    it('insert new rotating locker',()=>{
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click() // เพิ่มตู้
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click() // ชื่อคลัง
        cy.get('button[id="kb_language"]').should('be.visible').click() // เปลี่ยนภาษา
        cy.get('button[id="kb_ต"]').should('be.visible').click()
        cy.get('button[id="kb_้"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').eq(0).should('be.visible').click()
        cy.get('button[id="kb_ู"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').eq(0).should('be.visible').click()
        cy.get('button[id="kb_ห"]').should('be.visible').click()
        cy.get('button[id="kb_ม"]').should('be.visible').click()
        cy.get('button[id="kb_ุ"]').should('be.visible').click()
        cy.get('button[id="kb_น"]').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // A
        cy.get('button[class="btn btn-secondary"]').eq(2).should('be.visible').click() // B
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // A
        cy.get('button[class="btn btn-secondary"]').eq(2).should('be.visible').click() // B
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // A
        cy.get('button[class="btn btn-secondary"]').eq(2).should('be.visible').click() // B
        cy.get('button[class="btn btn-success"]').should('be.visible').click() // บันทึก
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click() // OK
    })
    it('insert new locker',()=>{
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click() // เพิ่มตู้
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click() // ชื่อคลัง
        cy.get('button[id="kb_language"]').should('be.visible').click() // เปลี่ยนภาษา
        cy.get('button[id="kb_ต"]').should('be.visible').click()
        cy.get('button[id="kb_้"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').eq(0).should('be.visible').click()
        cy.get('button[id="kb_ู"]').should('be.visible').click()
        cy.get('button[id="kb_ "]').should('be.visible').click()
        cy.get('button[id="kb_language"]').should('be.visible').click() // เปลี่ยนภาษา
        cy.get('button[id="kb_shift"]').eq(0).should('be.visible').click()
        cy.get('button[id="kb_L"]').eq(0).should('be.visible').click()
        cy.get('button[id="kb_shift"]').eq(0).should('be.visible').click()
        cy.get('button[id="kb_o"]').should('be.visible').click()
        cy.get('button[id="kb_c"]').should('be.visible').click()
        cy.get('button[id="kb_k"]').should('be.visible').click()
        cy.get('button[id="kb_e"]').should('be.visible').click()
        cy.get('button[id="kb_r"]').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('div[class="ant-select-selector"]').should('be.visible').click() // ประเภทตู้
        cy.get('div[title="Locker"]').should('be.visible').click() // ตู้ Locker
        cy.get('div[class="ant-select-selector"]').eq(1).should('be.visible').click() // ช่อง
        cy.get('div[title="01"]').should('be.visible').click() // ช่อง 01
        cy.get('div[class="ant-select-selector"]').eq(2).should('be.visible').click() // ความสูง
        cy.get('div[title="20"]').should('be.visible').click() // 20
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('div[class="ant-select-selector"]').eq(1).should('be.visible').click() // ช่อง
        cy.get('div[title="02"]').should('be.visible').click() // ช่อง 02
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-secondary"]').eq(1).should('be.visible').click() // สร้าง
        cy.get('button[class="btn btn-success"]').should('be.visible').click() // บันทึก
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click() // OK
    })
})