describe('RTMS Cost Center Test',()=>{
    it('select Cost Center',()=>{
        cy.wait(1000)
        cy.get('div[class="home"]').eq(5).should('be.visible').click() // ตั้งค่าขั้นสูง
        cy.get('div[class="home"]').eq(1).should('be.visible').click() // จัดการงาน
    })
    it('search TEST001 Cost Center',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_1"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
    })
    it('insert TEST001 Cost Center',()=>{
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[id="cost_center_header_name"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_1"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="ant-switch ant-switch-checked"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
    })
    it('search found TEST001 Cost Center',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_1"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
    })
    it('check data of TEST001',()=>{
        cy.get('a[class="btn btn-warning"]').should('be.visible').click()
        cy.wait(1000)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('update TEST001 to TEST002 and change data',()=>{
        cy.get('a[class="btn btn-warning"]').should('be.visible').click()
        cy.get('input[id="cost_center_header_name"]').should('be.visible').clear()
        cy.get('input[id="cost_center_header_name"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_2"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(2).should('be.visible').click()
        cy.get('button[class="ant-switch"]').should('be.visible').click()
        cy.get('td[class="text-info text-center align-middle"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(2).should('be.visible').click()
        cy.get('button[id="kb_p"]').contains('p').should('be.visible').click()
        cy.get('button[id="kb_u"]').contains('u').should('be.visible').click()
        cy.get('button[id="kb_r"]').contains('r').should('be.visible').click()
        cy.get('button[id="kb_i"]').contains('i').should('be.visible').click()
        cy.get('button[id="kb_n"]').contains('n').should('be.visible').click()
        cy.get('button[id="kb_4"]').contains('4').should('be.visible').click()
        cy.get('button[id="kb_5"]').contains('5').should('be.visible').click()
        cy.get('button[id="kb_6"]').contains('6').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
    })
    it('search not found TEST001',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_1"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
    })
    it('search found TEST002',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_2"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
    })
    it('check data of TEST002',()=>{
        cy.get('a[class="btn btn-warning"]').should('be.visible').click()
        cy.wait(1000)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('delete TEST002 Cost Center',()=>{
        cy.get('button[class="btn btn-danger"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
    })
    it('search not found TEST002',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_E"]').contains('E').should('be.visible').click()
        cy.get('button[id="kb_S"]').contains('S').should('be.visible').click()
        cy.get('button[id="kb_T"]').contains('T').should('be.visible').click()
        cy.get('button[id="kb_shift"]').contains('shift').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_0"]').contains('0').should('be.visible').click()
        cy.get('button[id="kb_2"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
    })
    it('check menu by disable Cost Center',()=>{
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click() // ย้อนกลับ
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการข้อมูลผู้ใช้
        cy.get('div[class="home"]').eq(1).should('be.visible').click() // จัดการสิทธิ์การใช้งาน
        cy.get('button[class="btn btn-info"]').eq(1).should('be.visible').click() // แก้ไข
        cy.scrollTo('bottom')
        cy.get('input[type="checkbox"]').eq(20).should('be.visible').click() // ปิด Cost Center
        cy.wait(3000)
        cy.get('button[class="btn btn-success"]').should('be.visible').click() // เพิ่ม
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click() // OK
    })
    it('test check menu by log out then log in',()=>{
        cy.get('div[class="b_logout"]').should('be.visible').click() // log out
        cy.wait(5000)
       cy.get('body').type('{1}{4}', { delay: 0 })
        cy.get('div[class="home"]').eq(5).should('be.visible').click() // ตั้งค่าขั้นสูง
        cy.log('Cannot found Cost Center')
        cy.wait(1000)
    })
    it('enable Cost Center',()=>{
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // จัดการข้อมูลผู้ใช้
        cy.get('div[class="home"]').eq(1).should('be.visible').click() // จัดการสิทธิ์การใช้งาน
        cy.get('button[class="btn btn-info"]').eq(1).should('be.visible').click() // แก้ไข
        cy.scrollTo('bottom')
        cy.get('input[type="checkbox"]').eq(20).should('be.visible').click() // เปิด Cost Center
        cy.wait(3000)
        cy.get('button[class="btn btn-success"]').should('be.visible').click() // เพิ่ม
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click() // OK
    })
    it('test check menu by log out then log in',()=>{
        cy.get('div[class="b_logout"]').should('be.visible').click() // log out
        cy.wait(5000)
       cy.get('body').type('{1}{4}', { delay: 0 })
        cy.get('div[class="home"]').eq(5).should('be.visible').click() // ตั้งค่าขั้นสูง
        cy.log('Found Cost center menu')
        cy.wait(1000)
    })
})