import "./1.login/1.rtms_login.spec";
// import "./2.product type/2.rtms_product_type.spec"
// import "./3.product group/3.rtms_product_group.spec"
// import "./4.product brand/4.rtms_product_brand.spec"
// import "./5.product manage unit/5.rtms_product_manage_unit.spec"
// import "./6.locker/6.rtms_locker.spec"
// import "./7.product/7.rtms_product.spec"
// import "./8.manage menu/8.rtms_manage_menu.spec"
// import "./9.product set/9.rtms_product_set.spec"
// import "./10.group access product/10.rtms_group_access_product.spec"
// import "./11.manage department/11.rtms_manage_department.spec"
// import "./12.manage license/12.rtms_manage_license.spec"
// import "./13.fix costcenter/13.rtms_fix_costcenter.spec"
// import "./14.manage user/14.rtms_manage_user.spec"
// import "./15.cost center/15.rtms_costcenter.spec"
// import "./16.qr code/16.rtms_qr_code.spec"
// import "./17.tools life/17.rtms_tools_life.spec"
// import "./18.manage job/18.rtms_manage_job.spec"
import "./19.fill product/19.rtms_fill_product.spec"