describe('RTMS QR Code Test',()=>{
    it('access RTMS',()=>{
        cy.wait(10000)
        cy.visit('http://localhost/rtms/#/')
        cy.wait(4000)
        cy.get('body').click().type('15',{delay: 10})
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.wait(2000)
        cy.get('body').click().type('14',{delay: 10})
    })
    it('add unit , product of PURIN1',()=>{
        cy.get('div[class="home"]').eq(6).should('be.visible').click() // ตั้งค่าขั้นสูง
        cy.get('div[class="home"]').eq(3).should('be.visible').click() // จัดการข้อมูลสินค้า
        cy.get('div[class="home"]').eq(6).should('be.visible').click() // จัดการหน่วยสินค้า
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('button[type="button"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // สินค้า
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[type="file"]').eq(0).should('be.visible').click()
        const filePath = '6.jpg'
        cy.get('input[type="file"]').attachFile(filePath);
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('label[class="ant-radio-button-wrapper"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('รหัสสินค้า ลูกค้า').parent().find('input').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('button[type="button"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('input[class="form-control"]').eq(2).should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('+').should('be.visible').click()
        cy.get('button[type="button"]').contains('_').should('be.visible').click()
        cy.get('button[type="button"]').contains('_').should('be.visible').click()
        cy.get('button[type="button"]').contains('+').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.contains('บาร์โค้ด').parent().find('button').should('be.visible').click()
        cy.contains('จัดการ').parent().find('input').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy.contains('เพิ่ม').get('button[class="btn btn-info"]').should('be.visible').should('be.visible').click()
        cy.contains('ตกลง').parent().find('button[class="btn btn-success"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ชื่อที่ใช้งาน ลูกค้า').parent().find('input').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ขนาดช่อง').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('input[class="form-check-input"]').eq(3).should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('กลุ่มสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('input[class="form-check-input"]').eq(0).should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ประเภทสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('input[type="radio"]').eq(6).should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('แบรนด์สินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('input[type="radio"]').eq(5).should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('Min').parent().find('input[class="float text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('Warning').parent().find('input[class="text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ประเภทสินค้าของการเบิก').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.contains('สิ้นเปลือง').get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('label[class="ant-radio-button-wrapper"]').eq(1).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ประเภทการเบิก').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.contains('เบิกแบบระบุจำนวน').get('td[class="ant-table-cell"]').eq(4).should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('จำนวนต่อการเติม').parent().find('input[class="text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ราคา').parent().find('input[class="float text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('หน่วยสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.wait(500)
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('insert Cost Center',()=>{
        cy.get('div[class="home"]').eq(1).should('be.visible').click() // จัดการงาน 
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[id="cost_center_header_name"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="ant-switch ant-switch-checked"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('search TEST001 QR Code',()=>{
        cy.scrollTo('bottom')
        cy.get('div[class="home"]').eq(13).should('be.visible').click() // จัดการ QR Code เบิกสินค้า
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('button[class="btn btn-info btn btn-secondary"]').should('be.visible').click() // ส่งอีเมล
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click() // OK
    })
    it('insert TEST001 QR Code',()=>{
        cy.get('button[class="btn btn-success btn btn-secondary"]').should('be.visible').click() // เพี่ม QR Code เบิกสินค้า
        cy.get('button[class="btn btn-success"]').should('be.visible').click() // บันทึก
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click() // OK
        cy.get('button[class="text-white btn btn-info text-center rounded"]').should('be.visible').click() // เลือกสินค้า
        cy.get('input[class="form-check-input"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').eq(1).should('be.visible').click()
        cy.wait(500)
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('button[type="button"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click() // บันทึก
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click() // OK
    })
    it('search found TEST001 QR Code',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
    })
    it('send Email QR Code',()=>{
        cy.get('button[class="btn btn-info btn btn-secondary"]').should('be.visible').click() // ส่งอีเมล
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click() // OK
        cy.scrollTo('top')
        cy.get('input[class="form-check-input"]').eq(1).should('be.visible').click()
        cy.scrollTo('top')
        cy.get('button[class="btn btn-info btn btn-secondary"]').should('be.visible').click() // ส่งอีเมล
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click()
        cy.get('button[type="button"]').contains('p').should('be.visible').click()
        cy.get('button[type="button"]').contains('u').should('be.visible').click()
        cy.get('button[type="button"]').contains('r').should('be.visible').click()
        cy.get('button[type="button"]').contains('i').should('be.visible').click()
        cy.get('button[type="button"]').contains('n').should('be.visible').click()
        cy.get('button[type="button"]').contains('s').should('be.visible').click()
        cy.get('button[type="button"]').contains('i').should('be.visible').click()
        cy.get('button[type="button"]').contains('r').should('be.visible').click()
        cy.get('button[type="button"]').contains('i').should('be.visible').click()
        cy.get('button[type="button"]').contains('p').should('be.visible').click()
        cy.get('button[type="button"]').contains('r').should('be.visible').click()
        cy.get('button[type="button"]').contains('u').should('be.visible').click()
        cy.get('button[type="button"]').contains('6').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('@').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('g').should('be.visible').click()
        cy.get('button[type="button"]').contains('m').should('be.visible').click()
        cy.get('button[type="button"]').contains('a').should('be.visible').click()
        cy.get('button[type="button"]').contains('i').should('be.visible').click()
        cy.get('button[type="button"]').contains('l').should('be.visible').click()
        cy.get('button[type="button"]').contains('.').should('be.visible').click()
        cy.get('button[type="button"]').contains('c').should('be.visible').click()
        cy.get('button[type="button"]').contains('o').should('be.visible').click()
        cy.get('button[type="button"]').contains('m').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
    })
})