describe('RTMS Product Test',()=>{
    it('access RTMS',()=>{
        cy.visit('http://localhost/rtms/#/')
        cy.wait(4000)
        cy.get('body').click().type('15',{delay: 10})
        cy.wait(1000)
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.wait(2000)
        cy.get('body').click().type('14',{delay: 10})
    })
    it('add group , unit of PURIN1',()=>{
        cy.get('div[class="home"]').eq(6).should('be.visible').click()
        cy.get('div[class="home"]').eq(3).should('be.visible').click()
        cy.get('div[class="home"]').eq(2).should('be.visible').click() // กลุ่มสินค้า
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.get('div[class="home"]').eq(6).should('be.visible').click() // จัดการหน่วยสินค้า
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('button[type="button"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.get('div[class="home"]').eq(6).should('be.visible').click() // จัดการหน่วยสินค้า
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('4').should('be.visible').click()
        cy.get('button[type="button"]').contains('5').should('be.visible').click()
        cy.get('button[type="button"]').contains('6').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('search PURIN1',()=>{
        cy.get('div[class="home"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').should('be.visible').click()
    })
    it('add PURIN1 , test validation',()=>{
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy
        cy.get('input[type="file"]').should('be.visible').click()
        cy
        const filePath = '6.jpg'
        cy.get('input[type="file"]').attachFile(filePath);
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('label[class="ant-radio-button-wrapper"]').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('รหัสสินค้า ลูกค้า').parent().find('input').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('button[type="button"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('input[class="form-control"]').eq(2).should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('+').should('be.visible').click()
        cy.get('button[type="button"]').contains('_').should('be.visible').click()
        cy.get('button[type="button"]').contains('_').should('be.visible').click()
        cy.get('button[type="button"]').contains('+').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.contains('บาร์โค้ด').parent().find('button').should('be.visible').click()
        cy.contains('จัดการ').parent().find('input').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy.contains('เพิ่ม').get('button[class="btn btn-info"]').should('be.visible').should('be.visible').click()
        cy.contains('ตกลง').parent().find('button[class="btn btn-success"]').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ชื่อที่ใช้งาน ลูกค้า').parent().find('input').should('be.visible').click()
        cy
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ขนาดช่อง').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.get('input[class="form-check-input"]').eq(3).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('กลุ่มสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.get('input[class="form-check-input"]').eq(1).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ประเภทสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.get('input[type="radio"]').eq(6).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('แบรนด์สินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.get('input[type="radio"]').eq(5).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('Min').parent().find('input[class="float text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('Warning').parent().find('input[class="text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ประเภทสินค้าของการเบิก').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.contains('สิ้นเปลือง').get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('label[class="ant-radio-button-wrapper"]').eq(1).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ประเภทการเบิก').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.contains('เบิกแบบระบุจำนวน').get('td[class="ant-table-cell"]').eq(4).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('จำนวนต่อการเติม').parent().find('input[class="text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ราคา').parent().find('input[class="float text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('สถานะ').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.contains('Inactive').get('td[class="ant-table-cell"]').eq(0).should('be.visible').click() // เมื่อบันทึกไปแล้วจะลบไม่ได้
        cy.contains('หน่วยสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(0).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
    })
    it('search found PURIN1',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
    })
    it('check Package 1',()=>{
        cy.get('button[class="btn btn-info"]').eq(2).should('be.visible').click()
        cy.scrollTo('bottom')
        cy.wait(1000)
        cy.scrollTo('top')
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('check Regrind 1',()=>{
        cy.get('button[class="btn btn-info"]').eq(3).should('be.visible').click()
        cy.scrollTo('bottom')
        cy.wait(1000)
        cy.scrollTo('top')
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('check PURIN1 product',()=>{
        cy.get('div[class="overflow-auto"]').scrollTo('right')
        cy.get('button[class="btn btn-info"]').eq(4).should('be.visible').click()
        cy.scrollTo('bottom')
        cy.wait(1000)
        cy.scrollTo('top')
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('test relation delete PURIN1',()=>{
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.get('div[class="home"]').eq(2).should('be.visible').click() // กลุ่มสินค้า
        cy.get('button[class="btn btn-danger"]').eq(1).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.get('div[class="home"]').eq(6).should('be.visible').click() // หน่วยสินค้า
        cy.get('button[class="btn btn-danger"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('update PURIN1 to PURIN2',()=>{
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // สินค้า
        cy.get('div[class="overflow-auto"]').scrollTo('right')
        cy.get('button[class="btn btn-info"]').eq(4).should('be.visible').click()
        cy.get('input[type="file"]').should('be.visible').click()
        cy
        const filePath = '5.jpg'
        cy.get('input[type="file"]').attachFile(filePath);
        cy.contains('หน่วยสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(1).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('รหัสสินค้า ลูกค้า').parent().find('input').should('be.visible').clear()
        cy.contains('รหัสสินค้า ลูกค้า').parent().find('input').should('be.visible').click()
        cy.get('button[type="button"]').contains('4').should('be.visible').click()
        cy.get('button[type="button"]').contains('5').should('be.visible').click()
        cy.get('button[type="button"]').contains('6').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.get('input[class="form-control"]').eq(2).should('be.visible').clear()
        cy.get('input[class="form-control"]').eq(2).should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('_').should('be.visible').click()
        cy.get('button[type="button"]').contains('_').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.scrollTo('top')
        cy.contains('บาร์โค้ด').parent().find('button').should('be.visible').click()
        cy.get('button[class="btn btn-danger"]').should('be.visible').click()
        cy.contains('จัดการ').parent().find('input').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('button[type="button"]').contains('9').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy.contains('เพิ่ม').get('button[class="btn btn-info"]').should('be.visible').should('be.visible').click()
        cy.contains('ตกลง').parent().find('button[class="btn btn-success"]').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('สถานะ').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.contains('Active').get('td[class="ant-table-cell"]').eq(2).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').contains('บันทึก').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ขนาดช่อง').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.get('input[class="form-check-input"]').eq(4).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('กลุ่มสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.get('input[class="form-check-input"]').eq(0).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ประเภทสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.get('input[type="radio"]').eq(5).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('แบรนด์สินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.get('input[type="radio"]').eq(4).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('Min').parent().find('input[class="float text-right form-control"]').should('be.visible').clear()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('Min').parent().find('input[class="float text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="text-right form-control"]').eq(0).should('be.visible').clear()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="text-right form-control"]').eq(0).should('be.visible').clear()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ประเภทการเบิก').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy
        cy.contains('เบิกแบบกำหนดจำนวนต่อการเบิก').get('td[class="ant-table-cell"]').eq(2).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="float text-right form-control"]').eq(2).should('be.visible').click()
        cy.get('button[type="button"]').contains('backspace').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="text-right form-control"]').eq(1).should('be.visible').click()
        cy.get('button[type="button"]').contains('backspace').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('ราคา').parent().find('input[class="float text-right form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('backspace').should('be.visible').click()
        cy.get('button[type="button"]').contains('backspace').should('be.visible').click()
        cy.get('button[type="button"]').contains('backspace').should('be.visible').click()
        cy.get('button[type="button"]').contains('backspace').should('be.visible').click()
        cy.get('button[type="button"]').contains('backspace').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('button[type="button"]').contains('7').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('input[class="form-control"]').eq(3).clear()
        cy.get('input[class="form-control"]').eq(3).click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.contains('หน่วยสินค้า').parent().find('button[class="d-flex align-items-center w-100 border-secondary bg-white btn btn-secondary"]').should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(2).should('be.visible').click()
        cy
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
    })
    it('search not found PURIN1',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
    })
    it('search found PURIN2',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
    })
    it('check Booking 2',()=>{
        // cy.get('div[class="home"]').eq(6).should('be.visible').click()
        // cy.get('div[class="home"]').eq(3).should('be.visible').click()
        // cy.get('div[class="home"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(1).should('be.visible').click() // จอง
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(0).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(0).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(1).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(1).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(2).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(2).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(3).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(3).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(4).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(4).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(20).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(20).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(21).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(21).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(22).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(22).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(23).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(23).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(255, 255, 255);"]').eq(24).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(255, 255, 255);"]').eq(24).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').eq(0).should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(1).should('be.visible')
    })
    it('check Package 2',()=>{
        cy.get('button[class="btn btn-info"]').eq(2).should('be.visible').click() // Package
        cy.scrollTo('bottom')
        cy.wait(1000)
        cy.scrollTo('top')
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('check Regrind 2',()=>{
        cy.get('button[class="btn btn-info"]').eq(3).should('be.visible').click() // Regrind
        cy.scrollTo('bottom')
        cy.wait(1000)
        cy.scrollTo('top')
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('check PURIN2 product',()=>{
        cy.get('div[class="overflow-auto"]').scrollTo('right')
        cy.get('button[class="btn btn-info"]').eq(4).should('be.visible').click()
        cy.scrollTo('bottom')
        cy.wait(1000)
        cy.scrollTo('top')
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('cancel Booking',()=>{
        cy.get('button[class="btn btn-info"]').eq(1).should('be.visible').click() // จอง
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(0).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(0).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(1).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(1).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(2).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(2).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(3).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(3).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(4).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(4).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(0).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(0).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(1).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(1).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(2).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(2).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(0).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(0).should('be.visible').click()
        cy.get('td[style="height: 30px; background: rgb(22, 190, 20);"]').eq(0).should('be.visible').click()
        cy.get('td[style="height: 60px; background: rgb(22, 190, 20);"]').eq(0).should('be.visible').click()
        cy.get('button[class="btn btn-success"]').should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').eq(0).should('be.visible').click()
        cy.get('td[class="ant-table-cell"]').eq(1).should('be.visible')
    })
    it('test relation delete PURIN2',()=>{
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.get('div[class="home"]').eq(2).should('be.visible').click() // กลุ่มสินค้า
        cy.get('button[class="btn btn-danger"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.get('div[class="home"]').eq(6).should('be.visible').click() // หน่วยสินค้า
        cy.get('button[class="btn btn-danger"]').eq(1).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
    it('delete PURIN2 product',()=>{
        cy.get('div[class="home"]').eq(0).should('be.visible').click() // สินค้า
        cy.get('div[class="overflow-auto"]').scrollTo('right')
        cy.get('button[class="btn btn-danger"]').should('be.visible').click()
        cy
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('div[class="overflow-auto"]').scrollTo('left')
    })
    it('search not found PURIN2',()=>{
        cy.get('input[class="form-control"]').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('P').should('be.visible').click()
        cy.get('button[type="button"]').contains('U').should('be.visible').click()
        cy.get('button[type="button"]').contains('R').should('be.visible').click()
        cy.get('button[type="button"]').contains('I').should('be.visible').click()
        cy.get('button[type="button"]').contains('N').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('input[class="form-control"]').should('be.visible').clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').click()
        cy.get('div[class="overflow-auto"]').scrollTo('left')
    })
    
    it('delete group and unit of PURIN1,2',()=>{
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.get('div[class="home"]').eq(2).should('be.visible').click() // กลุ่มสินค้า
        cy.get('button[class="btn btn-danger"]').eq(1).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
        cy.get('div[class="home"]').eq(6).should('be.visible').click() // จัดการหน่วยสินค้า
        cy.get('button[class="btn btn-danger"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-danger"]').eq(0).should('be.visible').click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').click()
        cy.get('button[class="btn btn-secondary"]').should('be.visible').click()
    })
})