describe('Software RTMS Product Manage Unit Test',()=>{
    it('access RTMS',()=>{
        cy.visit('http://localhost/rtms/#/')
        cy.wait(3000)
        cy.wait(3000)
        cy.get('body').click().type('15',{delay: 10})
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
        cy.wait(2000)
        cy.get('body').click().type('14',{delay: 10})
    })
    it('select advance option -> manage product -> manage product unit',()=>{
        cy.get('div[class="home"]').eq(6).should('be.visible').wait(300).click()
        cy.get('div[class="home"]').eq(3).should('be.visible').wait(300).click()
        cy.get('div[class="home"]').eq(6).should('be.visible').wait(300).click()
    })
    it('search PURIN1',()=>{
        cy.get('input[class="form-control"]').should('be.visible').wait(300).click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
        cy.get('input[class="form-control"]').should('be.visible').wait(300).clear()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
    })
    it('add PURIN1',()=>{
        cy.get('button[class="btn btn-success float-right btn btn-secondary"]').should('be.visible').wait(300).click()
        cy.get('button[class="btn btn-success"]').should('be.visible').wait(300).click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
        cy.get('input[class="text-right form-control"]').should('be.visible').wait(300).click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('button[type="button"]').contains('3').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').wait(300).click()
        cy.get('button[class="btn btn-success"]').should('be.visible').wait(300).click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').wait(300).click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').wait(300).click()
        cy.get('button[class="btn btn-success"]').should('be.visible').wait(300).click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
    })
    it('search found PURIN1',()=>{
        cy.get('input[class="form-control"]').should('be.visible').wait(300).click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
        cy.get('input[class="form-control"]').should('be.visible').wait(300).clear()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
    })
    it('check PURIN1 detail',()=>{
        cy.get('button[class="btn btn-info"]').eq(1).should('be.visible').wait(300).click()
        cy.wait(3000)
        cy.get('button[class="btn btn-success"]').should('be.visible').wait(300).click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
    })
    it('update PURIN1 to PURIN2',()=>{
        cy.get('button[class="btn btn-info"]').eq(1).should('be.visible').wait(300).click()
        cy.get('input[class="text-right form-control"]').should('be.visible').wait(300).clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').wait(300).click()
        cy.get('button[class="btn btn-success"]').should('be.visible').wait(300).click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
        cy.get('input[class="text-right form-control"]').should('be.visible').wait(300).click()
        cy.get('button[type="button"]').contains('4').should('be.visible').click()
        cy.get('button[type="button"]').contains('5').should('be.visible').click()
        cy.get('button[type="button"]').contains('6').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').wait(300).click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').wait(300).clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').wait(300).click()
        cy.get('button[class="btn btn-success"]').should('be.visible').wait(300).click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
        cy.get('input[class="form-control"]').eq(1).should('be.visible').wait(300).click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').wait(300).click()
        cy.get('button[class="btn btn-success"]').should('be.visible').wait(300).click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
    })
    it('search not found PURIN1',()=>{
        cy.get('input[class="form-control"]').should('be.visible').wait(300).click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('1').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
        cy.get('input[class="form-control"]').should('be.visible').wait(300).clear()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
    })
    it('search found PURIN2',()=>{
        cy.get('input[class="form-control"]').should('be.visible').wait(300).click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
        cy.get('input[class="form-control"]').should('be.visible').wait(300).clear()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
    })
    it('check PURIN2 detail',()=>{
        cy.get('button[class="btn btn-info"]').eq(1).should('be.visible').wait(300).click()
        cy.wait(3000)
        cy.get('button[class="btn btn-success"]').should('be.visible').wait(300).click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
    })
    it('delete PURIN2',()=>{
        cy.get('button[class="btn btn-danger"]').should('be.visible').wait(300).click()
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
        cy.wait(2000)
        cy.get('button[class="swal2-confirm swal2-styled"]').should('be.visible').wait(300).click()
    })
    it('search not found PURIN2',()=>{
        cy.get('input[class="form-control"]').should('be.visible').wait(300).click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('E').should('be.visible').click()
        cy.get('button[type="button"]').contains('S').should('be.visible').click()
        cy.get('button[type="button"]').contains('T').should('be.visible').click()
        cy.get('button[type="button"]').contains('shift').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('0').should('be.visible').click()
        cy.get('button[type="button"]').contains('2').should('be.visible').click()
        cy.get('i[class="fa fa-times"]').should('be.visible').wait(300).click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
        cy.get('input[class="form-control"]').should('be.visible').wait(300).clear()
        cy.get('i[class="fa fa-times"]').should('be.visible').wait(300).click()
        cy.get('button[class="btn btn-info"]').eq(0).should('be.visible').wait(300).click()
    })
})